title: Titulo
author: Nestor G
email: nestoralons42gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Descripcion

# social links
twitter_username: your-ggtwitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-gggithub-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme:minima
