title: "titulo"
author: "Nestoralons"
email: "nestoralons"
description: "titulo perron"

# social links
twitter_username: yddfde # DO NOT include the @ character, or else the build will fail!
github_username:  yofgfe # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
