title: "titulo"
author: "Nestoralons"
email: "nestoralons"
description:> # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  titulo perron

# social links
twitter_username: yddfde # DO NOT include the @ character, or else the build will fail!
github_username:  yofgfe # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
